package auth

import (
	"net/http"
)

// IdentifyPayload contains user information and redirect URL for Intercom identification.
// Note: We don't include Auth0's 'sub' claim as it's not safe to use as username.
// The authoritative user identity is in the IntercomJWT (generated by Auth0 Action).
type IdentifyPayload struct {
	ReturnTo    string
	Email       string
	Name        string
	IntercomJWT string // Pre-generated Intercom JWT from Auth0 Action
}

// IdentifyRenderer handles rendering the authentication response.
// This interface allows for vendor-neutral identity management.
type IdentifyRenderer interface {
	Render(w http.ResponseWriter, p IdentifyPayload) error
}
